package com.apyan.to_dolist.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.apyan.to_dolist.util.Constants.DATABASE_TABLE

@Entity(tableName = DATABASE_TABLE)
data class ToDoTask(
    // Auto-generated by Room library
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String,
    val description: String,
    val priority: Priority
)